name: Trufflehog security scan

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches-ignore:
      - master

jobs:
  vulnerability-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up TruffleHog
        run: |
          sudo apt-get update && sudo apt-get install -y git curl jq
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Run TruffleHog Scan
        env:
          SCAN_PATH: "."
        run: |
          trufflehog filesystem "$SCAN_PATH" --only-verified --fail --json | jq .
