name: Trufflehog security scan

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches-ignore:
      - master

jobs:
  vulnerability-detection:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          ### Alpine 3.17
          - image: "alpine/3.17/8.1/Dockerfile"
            tags: "8.1-alpine3.17"
            platforms: "linux/amd64"
          - image: "alpine/3.17/8.2/Dockerfile"
            tags: "8.2-alpine3.17"
            platforms: "linux/amd64"
          - image: "alpine/3.17/8.3/Dockerfile"
            tags: "8.3-alpine3.17"
            platforms: "linux/amd64"

          ### Alpine 3.18
          - image: "alpine/3.18/8.1/Dockerfile"
            tags: "8.1-alpine3.18"
            platforms: "linux/amd64"
          - image: "alpine/3.18/8.2/Dockerfile"
            tags: "8.2-alpine3.18"
            platforms: "linux/amd64"
          - image: "alpine/3.18/8.3/Dockerfile"
            tags: "8.3-alpine3.18"
            platforms: "linux/amd64"

          ### Alpine 3.19
          - image: "alpine/3.19/8.1/Dockerfile"
            tags: "8.1-alpine3.19"
            platforms: "linux/amd64"
          - image: "alpine/3.19/8.2/Dockerfile"
            tags: "8.2-alpine3.19"
            platforms: "linux/amd64"
          - image: "alpine/3.19/8.3/Dockerfile"
            tags: "8.3-alpine3.19"
            platforms: "linux/amd64"

          ### Alpine 3.20
          - image: "alpine/3.20/8.1/Dockerfile"
            tags: "8.1-alpine3.20"
            platforms: "linux/amd64"
          - image: "alpine/3.20/8.2/Dockerfile"
            tags: "8.2-alpine3.20"
            platforms: "linux/amd64"
          - image: "alpine/3.20/8.3/Dockerfile"
            tags: "8.3-alpine3.20"
            platforms: "linux/amd64"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up TruffleHog
        run: |
          sudo apt-get update && sudo apt-get install -y git curl jq
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Run TruffleHog Scan
        env:
          SCAN_PATH: "."
        run: |
          trufflehog filesystem "$SCAN_PATH" --only-verified --fail --json | jq .
