name: Build and Scan Docker Images with Trivy && Trufflehog

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-scan-images-for-vulnerabilities:
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          ### Alpine 3.19
          - context: "alpine/3.19/8.1"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.1-alpine3.19"
            platforms: "linux/amd64"
          - context: "alpine/3.19/8.2"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.2-alpine3.19"
            platforms: "linux/amd64"
          - context: "alpine/3.19/8.3"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.3-alpine3.19"
            platforms: "linux/amd64"

          ### Alpine 3.20
          - context: "alpine/3.20/8.1"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.1-alpine3.20"
            platforms: "linux/amd64"
          - context: "alpine/3.20/8.2"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.2-alpine3.20"
            platforms: "linux/amd64"
          - context: "alpine/3.20/8.3"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.3-alpine3.20"
            platforms: "linux/amd64"

          ### Alpine 3.21
          - context: "alpine/3.21/8.2"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.2-alpine3.21"
            platforms: "linux/amd64"
          - context: "alpine/3.21/8.3"
            dockerfile: "Dockerfile"
            image: "spryker/php:8.3-alpine3.21"
            platforms: "linux/amd64"

    name: Build and Scan - ${{ matrix.image }}
    uses: spryker-projects/gha-reusable-workflows/.github/workflows/trivy-trufflehog-default-security-scan.yml@main
    with: 
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      image: ${{ matrix.image }}
      platforms: ${{ matrix.platforms }}
    secrets: inherit
