name: Build and Scan Docker Images with Trivy && Trufflehog

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_scan:
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          ### Alpine 3.19
          - context: "alpine/3.19/8.1"
            dockerfile: "Dockerfile"
            tag: "8.1-alpine3.19"
            platforms: "linux/amd64"
          - context: "alpine/3.19/8.2"
            dockerfile: "Dockerfile"
            tag: "8.2-alpine3.19"
            platforms: "linux/amd64"
          - context: "alpine/3.19/8.3"
            dockerfile: "Dockerfile"
            tag: "8.3-alpine3.19"
            platforms: "linux/amd64"

          ### Alpine 3.20
          - context: "alpine/3.20/8.1"
            dockerfile: "Dockerfile"
            tag: "8.1-alpine3.20"
            platforms: "linux/amd64"
          - context: "alpine/3.20/8.2"
            dockerfile: "Dockerfile"
            tag: "8.2-alpine3.20"
            platforms: "linux/amd64"
          - context: "alpine/3.20/8.3"
            dockerfile: "Dockerfile"
            tag: "8.3-alpine3.20"
            platforms: "linux/amd64"

          ### Alpine 3.21
          - context: "alpine/3.21/8.2"
            dockerfile: "Dockerfile"
            tag: "8.2-alpine3.21"
            platforms: "linux/amd64"
          - context: "alpine/3.21/8.3"
            dockerfile: "Dockerfile"
            tag: "8.3-alpine3.21"
            platforms: "linux/amd64"

    name: Build and Scan - ${{ matrix.tag }}
    uses: DenysSirchenko/gha_workflows/.github/workflows/ecr-scheduled-security-scan.yml@main
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
    secrets: inherit
