name: Build and Scan Docker Images with Trivy && Trufflehog

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-images-for-vulnerabilities:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          # ### Alpine 3.19
          # - context: "alpine/3.19/8.1"
          #   dockerfile: "Dockerfile"
          #   tags: "8.1-alpine3.19"
          #   platforms: "linux/amd64"
          # - context: "alpine/3.19/8.2"
          #   dockerfile: "Dockerfile"
          #   tags: "8.2-alpine3.19"
          #   platforms: "linux/amd64"
          # - context: "alpine/3.19/8.3"
          #   dockerfile: "Dockerfile"
          #   tags: "8.3-alpine3.19"
          #   platforms: "linux/amd64"

          # ### Alpine 3.20
          # - context: "alpine/3.20/8.1"
          #   dockerfile: "Dockerfile"
          #   tags: "8.1-alpine3.20"
          #   platforms: "linux/amd64"
          # - context: "alpine/3.20/8.2"
          #   dockerfile: "Dockerfile"
          #   tags: "8.2-alpine3.20"
          #   platforms: "linux/amd64"
          # - context: "alpine/3.20/8.3"
          #   dockerfile: "Dockerfile"
          #   tags: "8.3-alpine3.20"
          #   platforms: "linux/amd64"

          ### Alpine 3.18
          - context: "alpine/3.21/8.2"
            dockerfile: "Dockerfile"
            tags: "8.2-alpine3.21"
            platforms: "linux/amd64"
          - context: "alpine/3.21/8.3"
            dockerfile: "Dockerfile"
            tags: "8.3-alpine3.21"
            platforms: "linux/amd64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        id: build_images
        run: |
          images=()
          for image in "${{ toJson(matrix.include) }}"; do
            tag=$(echo "$image" | jq -r '.tags')
            docker build --platform ${{ matrix.platforms }} -t spryker/php:${tag} -f ${{ matrix.context }}/${{ matrix.dockerfile }} .
            images+=("spryker/php:${tag}")
          done
          echo "Built images: $images"
          echo "::set-output name=built_images::$(IFS=,; echo "${images[*]}")"

  scan-images-for-vulnerabilities:
    needs: build-images-for-vulnerabilities
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_url: ${{ fromJson(needs.build-images-for-vulnerabilities.outputs.built_images) }}

    steps:
      - name: Scan Docker image with Trufflehog and Trivy
        uses: DenysSirchenko/gha_workflows/.github/workflows/ecr-scheduled-security-scan.yml@main
        with:
          image_url: ${{ matrix.image_url }}
